const csQuestions = [
  {
    text: "What does CPU stand for?",
    answerChoices: [
      { text: "Central Processing Unit", isCorrect: true },
      { text: "Computer Personal Unit", isCorrect: false },
      { text: "Central Performance Unit", isCorrect: false },
      { text: "Control Processing Unit", isCorrect: false },
      { text: "Computer Processing Unit", isCorrect: false },
      { text: "Central Power Unit", isCorrect: false },
      { text: "Control Power Unit", isCorrect: false },
      { text: "Computer Power Unit", isCorrect: false },
    ],
  },
  {
    text: "What is the main function of RAM in a computer?",
    answerChoices: [
      { text: "Temporary data storage for quick access", isCorrect: true },
      { text: "Permanent data storage", isCorrect: false },
      { text: "Processing data", isCorrect: false },
      { text: "Managing power supply", isCorrect: false },
      { text: "Controlling input/output operations", isCorrect: false },
      { text: "Running the operating system", isCorrect: false },
      { text: "Storing software applications", isCorrect: false },
      { text: "Handling network connections", isCorrect: false },
    ],
  },
  {
    text: "What does HTTP stand for?",
    answerChoices: [
      { text: "HyperText Transfer Protocol", isCorrect: true },
      { text: "HyperText Transmission Protocol", isCorrect: false },
      { text: "HighText Transfer Protocol", isCorrect: false },
      { text: "HyperTransfer Text Protocol", isCorrect: false },
      { text: "HyperText Transfer Program", isCorrect: false },
      { text: "High Transfer Text Protocol", isCorrect: false },
      { text: "HyperText Transmission Program", isCorrect: false },
      { text: "HighText Transmission Protocol", isCorrect: false },
    ],
  },
  {
    text: "Which programming language is primarily used for web development?",
    answerChoices: [
      { text: "JavaScript", isCorrect: true },
      { text: "Python", isCorrect: false },
      { text: "C++", isCorrect: false },
      { text: "Java", isCorrect: false },
      { text: "Ruby", isCorrect: false },
      { text: "Swift", isCorrect: false },
      { text: "Go", isCorrect: false },
      { text: "PHP", isCorrect: false },
    ],
  },
  {
    text: "What does SQL stand for?",
    answerChoices: [
      { text: "Structured Query Language", isCorrect: true },
      { text: "Simple Query Language", isCorrect: false },
      { text: "Structured Question Language", isCorrect: false },
      { text: "Simple Question Language", isCorrect: false },
      { text: "Sequential Query Language", isCorrect: false },
      { text: "Standard Query Language", isCorrect: false },
      { text: "Structured Query Logic", isCorrect: false },
      { text: "Simple Query Logic", isCorrect: false },
    ],
  },
  {
    text: "What is the purpose of an IP address?",
    answerChoices: [
      { text: "To identify a device on a network", isCorrect: true },
      { text: "To store data", isCorrect: false },
      { text: "To process information", isCorrect: false },
      { text: "To manage power supply", isCorrect: false },
      { text: "To run applications", isCorrect: false },
      { text: "To control input/output operations", isCorrect: false },
      { text: "To connect to the internet", isCorrect: false },
      { text: "To secure data", isCorrect: false },
    ],
  },
  {
    text: "Which of the following is a version control system?",
    answerChoices: [
      { text: "Git", isCorrect: true },
      { text: "Docker", isCorrect: false },
      { text: "Kubernetes", isCorrect: false },
      { text: "Jenkins", isCorrect: false },
      { text: "Travis CI", isCorrect: false },
      { text: "Ansible", isCorrect: false },
      { text: "Puppet", isCorrect: false },
      { text: "Chef", isCorrect: false },
    ],
  },
  {
    text: "What does CSS stand for?",
    answerChoices: [
      { text: "Cascading Style Sheets", isCorrect: true },
      { text: "Computer Style Sheets", isCorrect: false },
      { text: "Creative Style Sheets", isCorrect: false },
      { text: "Coded Style Sheets", isCorrect: false },
      { text: "Cascading System Sheets", isCorrect: false },
      { text: "Computer System Sheets", isCorrect: false },
      { text: "Creative System Sheets", isCorrect: false },
      { text: "Coded System Sheets", isCorrect: false },
    ],
  },
  {
    text: "What is the main purpose of an operating system?",
    answerChoices: [
      {
        text: "To manage computer hardware and software resources",
        isCorrect: true,
      },
      { text: "To store data", isCorrect: false },
      { text: "To process information", isCorrect: false },
      { text: "To control network connections", isCorrect: false },
      { text: "To run applications", isCorrect: false },
      { text: "To manage power supply", isCorrect: false },
      { text: "To handle input/output operations", isCorrect: false },
      { text: "To secure data", isCorrect: false },
    ],
  },
  {
    text: "Which of the following is NOT a programming paradigm?",
    answerChoices: [
      { text: "Object-Oriented Programming", isCorrect: false },
      { text: "Functional Programming", isCorrect: false },
      { text: "Procedural Programming", isCorrect: false },
      { text: "Logical Programming", isCorrect: false },
      { text: "Declarative Programming", isCorrect: false },
      { text: "Imperative Programming", isCorrect: false },
      { text: "Concurrent Programming", isCorrect: false },
      { text: "Sequential Programming", isCorrect: true },
    ],
  },
];

export { csQuestions };
